In [8]:
import torch
import numpy as np

In [32]:
conv_layer2d = torch.nn.Conv2d(in_channels=1,out_channels=1,kernel_size=3)

In [33]:
conv_layer2d.weight.shape

torch.Size([1, 1, 3, 3])

![SegmentLocal](conv2d.gif "segment")

In [34]:
conv_layer2d(torch.ones((1,1,5,5)))

tensor([[[[1.3958, 1.3958, 1.3958],
          [1.3958, 1.3958, 1.3958],
          [1.3958, 1.3958, 1.3958]]]], grad_fn=<MkldnnConvolutionBackward>)

In [19]:
conv_layer2d(torch.ones((1,1,51,51)))

tensor([[[[0.7516, 0.7516],
          [0.7516, 0.7516]]]], grad_fn=<MkldnnConvolutionBackward>)

In [30]:
conv_layer2d = torch.nn.Conv2d(in_channels=1,out_channels=1,kernel_size=6,dilation=2)

![SegmentLocal](conv2dtialated.gif "segment")

In [31]:
conv_layer2d(torch.ones((1,1,13,13)))

tensor([[[[0.0788, 0.0788, 0.0788],
          [0.0788, 0.0788, 0.0788],
          [0.0788, 0.0788, 0.0788]]]], grad_fn=<SlowConvDilated2DBackward>)