In [107]:
import torch
import numpy as np

In [175]:
conv_layer = torch.nn.Conv1d(in_channels=1,out_channels=1,kernel_size=(10))
conv_layer2d = torch.nn.Conv2d(in_channels=1,out_channels=1,kernel_size=50)

In [176]:
conv_layer.weight.shape

torch.Size([1, 1, 50])

In [177]:
conv_layer2d.weight.shape

torch.Size([1, 1, 50, 50])

In [151]:
conv_layer2d.weight.data = conv_layer.weight.data

In [158]:
conv_layer2d.bias.data = conv_layer.bias.data

In [159]:
conv_layer(torch.ones((1,1,50,50)))

tensor([[[[-0.2506]]]], grad_fn=<MkldnnConvolutionBackward>)

In [160]:
conv_layer2d(torch.ones((1,1,50,50)))

tensor([[[[-0.2506]]]], grad_fn=<MkldnnConvolutionBackward>)

In [171]:
conv_layer(torch.ones((1,1,52,52)))

RuntimeError: Expected 3-dimensional input for 3-dimensional weight 1 1 50, but got 4-dimensional input of size [1, 1, 52, 52] instead

In [167]:
conv_layer2d(torch.ones((1,1,52,52)))

tensor([[[[-0.2506, -0.2506, -0.2506],
          [-0.2506, -0.2506, -0.2506],
          [-0.2506, -0.2506, -0.2506]]]], grad_fn=<MkldnnConvolutionBackward>)

In [164]:
i=  torch.randn(20, 16, 50)

In [165]:
i.shape

torch.Size([20, 16, 50])